import {
  gameMusicAssetId,
  invaderBaseAssetIds,
  menuMusicAssetId,
} from "./assetConfig.js";

export const designerAssetIds = [
  "hero.ship",
  ...invaderBaseAssetIds,
  "laser.blue",
  "laser.red",
  "background.space",
  "background.stars",
  "ui.panel",
  "ui.button",
  "audio.sfx.player-laser",
  "audio.sfx.invader-explosion",
  "audio.sfx.alien-laser",
  "audio.sfx.hero-hit",
  "audio.sfx.hero-explosion",
  "audio.sfx.game-over",
  menuMusicAssetId,
  gameMusicAssetId,
  "voice.announcer"
];

export const designerPreviewDisplaySize = {
  "hero.ship": { width: 54, height: 54 },
  "hero.ship.idle": { width: 54, height: 54 },
  "hero.ship.moving-left": { width: 54, height: 54 },
  "hero.ship.shooting": { width: 54, height: 54 },
  "hero.ship.hit": { width: 54, height: 54 },
  "hero.ship.explosion": { width: 54, height: 54 },
  "invader.scout": { width: 42, height: 42 },
  "invader.scout.idle": { width: 42, height: 42 },
  "invader.scout.shooting": { width: 42, height: 42 },
  "invader.scout.destroyed": { width: 42, height: 42 },
  "invader.scout.celebration": { width: 42, height: 42 },
  "invader.raider": { width: 42, height: 42 },
  "invader.raider.idle": { width: 42, height: 42 },
  "invader.raider.shooting": { width: 42, height: 42 },
  "invader.raider.destroyed": { width: 42, height: 42 },
  "invader.raider.celebration": { width: 42, height: 42 },
  "invader.hunter": { width: 42, height: 42 },
  "invader.hunter.idle": { width: 42, height: 42 },
  "invader.hunter.shooting": { width: 42, height: 42 },
  "invader.hunter.destroyed": { width: 42, height: 42 },
  "invader.hunter.celebration": { width: 42, height: 42 },
  "laser.blue": { width: 4, height: 18 },
  "laser.blue.flicker": { width: 4, height: 18 },
  "laser.blue.hit": { width: 18, height: 18 },
  "laser.red": { width: 5, height: 16 },
  "laser.red.flicker": { width: 5, height: 16 },
  "laser.red.hit": { width: 18, height: 18 },
  "ui.panel": { width: 180, height: 115 },
  "ui.button": { width: 190, height: 58 },
  "ui.button.idle": { width: 190, height: 58 },
  "ui.button.hover": { width: 190, height: 58 },
  "ui.button.clicked": { width: 190, height: 58 },
  "background.space": { width: 180, height: 180 },
  "background.space.mobile-portrait": { width: 101, height: 180 },
  "background.space.wide": { width: 240, height: 180 },
  "background.stars": { width: 32, height: 32 },
  "background.stars.twinkle-white": { width: 32, height: 32 },
  "background.stars.blue-pulse": { width: 32, height: 32 },
  "background.stars.gold-flare": { width: 32, height: 32 },
  "background.stars.violet-blink": { width: 32, height: 32 },
  "background.stars.green-shimmer": { width: 32, height: 32 }
};
